export type ProposalPdfData = {
  businessName: string;
  tradeType: string | null;
  contactEmail: string | null;
  phone: string | null;
  website: string | null;
  proposalNumber: string;
  createdAt: string;
  customerName: string | null;
  customerAddress: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  projectSummary: string;
  scopeOfWork: string[];
  materials: string[];
  labour: string | null;
  thingsToConfirm: string[];
  thingsToConfirmText: string | null;
  optionalExtras: string;
  estimatedPrice: number;
  estimatedDuration: string;
  durationNote: string | null;
  paymentTerms: string;
};
